### ISSUE TITLE
Clippings does not fully simulate a paste action

### ISSUE THREAD

**Issue by harry-wg** [aecreations/clippings#289] opened 2020-02-11 10:54 UTC
I've found two situations where information inserted from clippings is not fully recognised by web pages.

- input fields sometimes behave as if nothing was inserted, unless I follow the insert with a manually keyed **space backspace** pair

- textareas sometimes "lose" the inserted content if the insert is the last action before submitting the form

I'm guessing that in both cases, the inserted text is placed into the input field or text area without raising any of the events that the web page may be monitoring, and therefore the web page behaves as if the inserted information were not there.

Example: the compose window of any flarum-based forum

- In firefox (windows, desktop version), go to https://preview.community.giffgaff.com/d/124-firefox-clippings which is a placeholder I've created in the developer's preview of the giffgaff forum. You can safely test there without upsetting anybody but you will need to create a giffgaff ID to be able to post there
- click on **reply** 
- click on the **eye** icon alongside the post reply button
- observe that anything you type in the compose window is immediately copied into the preview window
- now try pasting a phrase from the windows clipboard using control-V. Observe that too is copied into the preview
- try inserting a phrase from clippings and observe that although the text appears in the compose window, it is not copied to the preview
- without adding any further text, click on **post message** and observe that the message has been submitted without the clippings text.

This matters, because we frequently use clippings to enter a final sentence in a reply, which therefore never appears.

I see similar problems pasting clippings in other forums, eg https://techforum.tfl.gov.uk/, but the giffgaff forum is one with active development and an area we can test without upsetting anybody.

**Why this happens?**

If I right click in the compose window and select Inspect Element, I see the events that the page is listening for -- I've posted them as an image at https://preview.community.giffgaff.com/d/124-firefox-clippings/2

I'm guessing that flarum needs at least the **paste** event to recognise that the textarea contents have changed and that clippings does not simulate that. So, the preview does not update and if the clipping is the last item in the window, it does not save into the reply.

I'm not sure if firefox allows extensions to raise events, but if it's possible for Clippings to raise the paste event, then I'm guessing this problem might be solved.

**Comment by aecreations** [comment] 2020-02-13 05:10
Thank you for the detailed description and analysis! I'll investigate further once I get the chance.

**Comment by aecreations** [comment] 2020-02-24 06:45
The cause was traced to the "input" event not being fired when a clipping is inserted (pasted). Will need to do further testing to ensure that pasting a clipping isn't impacted in commonly-used websites (e.g. Gmail, Outlook.com).

**Comment by aecreations** [comment] 2020-02-25 06:44
The bug fix will be available in the next release of Clippings.

**Comment by aecreations** [comment] 2020-03-19 03:06
Fixed in 6.2.1

**Closed by aecreations** 2020-03-19 03:06 UTC
Labels: bug, fixed
