### ISSUE TITLE
Pasting clipping into Gmail message editor doesn't work on Clippings 5.1

### ISSUE THREAD

**Issue by eoninc** [aecreations/clippings#71] opened 2016-07-28 19:59 UTC
I've used this software for years, but as of today, the basic function of right-clicking, selecting a specific clipping file and pasting it into a Firefox window is no longer functioning.  I've tried disabling and then re-enabling the Clipping add-on, restarting the computer, etc., but nothing changes.  So, there is no way to use this product to paste in the hundreds of clippings files that I have saved and used to use throughout the day up until just today--  7.28.16.  The version of Firefox I'm using is 47.0.1

Thanks in advance for any assistance to get this working again.

**Comment by aecreations** [comment] 2016-07-29 05:09
Which version of Clippings are you using?

What other add-ons do you have installed?  Try disabling all of them except for Clippings and see if the right-click context menu is working again.  If so, then re-enable the other add-ons one by one until it stops working; make note of which add-on was enabled when this happens.

One more thing you could try to help troubleshoot: start Firefox, when open the browser console (Tools -> Web Developer -> Browser Console), and look for any error messages originating from Clippings.

**Comment by bschmalhofer** [comment] 2016-07-29 12:27
I have seen the same effect with Clipping 5.1. It looks like this only happens with websites that are using frames.

**Comment by eoninc** [comment] 2016-07-29 14:03
Thanks for your reply.

I'm using the 5.1 version of Clippings.  I only use it with Google Gmail
for my email account and I've been using it that way for years.  This has
never happened before until yesterday.

I disabled all of the other Add-ons and I'm still getting the same
problem.  Here are the other add-ons I'm using:

[image: Inline image 1]
​I also tried the browser console as you suggested and this is all it is
showing:

[image: Inline image 2]​


​Thanks again for any assistance you can provide.

Michael​


*Michael De La Rosa*
Director of Operations & Technology
Texas Land Title Association
1717 West 6th St., Suite 120
Austin, Texas 78703
512.879.2890 (Direct) | 512.472.6593 (TLTA Main)
michael@tlta.com | www.tlta.com

<http://www.tlta.com/tlta/advocacy/texas_title_insurance_works_toolbox.aspx>

**Comment by aecreations** [comment] 2016-07-29 23:57
Thanks for the info.  I'll need to investigate/troubleshoot further.

**Comment by aecreations** [comment] 2016-07-30 00:29
See this post in the AE Creations blog for instructions on a workaround: http://aecreations.blogspot.ca/2016/07/issues-with-clippings-51-in-gmails.html

**Comment by bschmalhofer** [comment] 2016-07-30 09:16
Here is my setup. I'm running firefox 47.0 and Clippings 5.1.  On a website with HTML-frames I can't copy the selected text. When I try it I get the German message: "Keine Textauswahl vorhanden. Bitte zunächst den gewünschten Text auswählen.".
The problem disappears when I open the frame in a new browser tab and select the same text in the new tab.

**Comment by aecreations** [comment] 2016-07-30 23:48
Thanks for the details @bschmalhofer - this will be handled in a separate bug, issue #72.

**Comment by aecreations** [comment] 2016-08-01 07:32
Fixed in Clippings 5.1.1

**Closed by aecreations** 2016-08-01 07:32 UTC
Labels: bug, fixed

**Comment by eoninc** [comment] 2016-10-18 17:17
Just following up on this support request from a couple of months back...

The issue of being able to paste in an existing clipping was resolved with
one of the newer versions of the software that was released following my
original email about this.

However...

I'm now using Office 365 as an email client via my same Firefox browser,
and when I'm in the web version of Outlook, I'm no longer able to select
the text of a new message, right-click and then select 'New From
Selection'.    It still works just fine if I'm using Gmail, but when using
the web-based version of Outlook with Office 365, this functionality is no
longer there.  When I select this option, nothing happens at all.

Thanks in advance for any assistance you can lend on this issue.


Best regards,

Michael

*Michael De La Rosa, J.D., MBA*
Director of Operations & Technology
Texas Land Title Association
1717 West 6th St., Suite 120
Austin, Texas 78703
512.879.2890 (Direct) | 512.472.6593 (TLTA Main)
michael@tlta.com | www.tlta.com

<http://www.tlta.com/tlta/advocacy/texas_title_insurance_works_toolbox.aspx>

**Comment by aecreations** [comment] 2016-10-20 04:15
@eoninc - I don't have access to Office 365; is there a test account I can use to try to replicate the problem?

I'm unable to reproduce this issue on Outlook.com, both when composing a new email message and from an email message in the inbox.  I'm using Clippings 5.1.1 on Firefox Developer Edition version 51.

**Comment by aecreations** [comment] 2016-10-20 04:27
I have noticed, however, that when multi-process tabs are turned off, the Clippings submenu is missing from the browser's context menu when right-clicking on an empty message.  Screen shot attached. @eoninc, is this the issue you are experiencing? 

![outlook com - missing clippings submenu](https://cloud.githubusercontent.com/assets/6262753/19546202/8f63f4b6-9642-11e6-93cf-c1f22717d50a.png)

However, the Clippings submenu does appear on the context menu when there is text entered in the message body.

**Comment by aecreations** [comment] 2016-10-21 06:04
I tried again, this time using FIrefox on Mac OS X, and I notice that the version of Outlook.com is different.  Here, I am able to reproduce the issue; selecting Clippings -> New From Selection when attempting to create a clipping from a new email message has no effect.

This will be handled as a separate bug.  See issue #77.

Workaround: Drag and drop the selected text into the Clippings toolbar button.

**Comment by eoninc** [comment] 2016-11-29 19:59
I had a strange thing happen with my Clippings software today and hoping
you might be able to help restore it here.


I came across a Firefox support page suggesting that executing a Firefox
'Refresh' which is option from the tools menu, would help sluggish
performance of the browser.  But, after performing this Refresh and
re-launching Firefox, my Clippings extension was no longer there.  So, I
re-installed it but now all of my previously stored clippings are gone.

So, my question is--  Can I somehow restore the old clippings file that I
had earlier today and now appears to be gone?

Thanks in advance for your assistance.

Best regards,

Michael


*Michael De La Rosa, J.D., MBA*
Director of Operations & Technology
Texas Land Title Association
1717 West 6th St., Suite 120
Austin, Texas 78703
512.879.2890 (Direct) | 512.472.6593 (TLTA Main)
michael@tlta.com | www.tlta.com

<http://www.tlta.com/tlta/advocacy/texas_title_insurance_works_toolbox.aspx>

**Comment by aecreations** [comment] 2016-11-30 05:19
You may be able to restore your clippings if the ".clipbak" folder in your Firefox profile folder is still intact.  If it is, copy it to another location, then open Clippings Manager, choose Tools -> Import, then locate the most recent backup file from that folder.

P.S.: Please direct further questions about Clippings to the [AE Creations Help and Support Forums](https://groups.google.com/forum/#!forum/aecreations-help), and avoid adding comments not pertaining to the original issue, i.e., pasting clipping into Gmail message editor doesn't work on Clippings 5.1.  Thank you.
