### ISSUE TITLE
Clippings not working on Firefox Developer Edition (44.0a2)

### ISSUE THREAD

**Issue by kamidev** [aecreations/clippings#42] opened 2015-11-05 03:30 UTC
Stopped working after update to Firefox 44.0a2. 

Tested on OS X 10.11.1.

**Comment by aecreations** [comment] 2015-11-05 05:48
Try turning off Electrolysis (a.k.a. multi-process tabs).  Clippings is not yet compatible with it.  There will be a future update (beyond the 5.0 release) to make it compatible.

**Comment by kamidev** [comment] 2015-11-05 06:04
Thanks for the suggestion! That doesn't seem to help, unfortunately.

**Comment by aecreations** [comment] 2015-11-05 06:08
You reported that Clippings had "stopped working."  Please specify exactly what problems you are seeing.

**Comment by kamidev** [comment] 2015-11-05 06:35
Clicking the toolbar button does nothing. Dragging selected text to the toolbar button does nothing. The keyboard shortcut does nothing.

**Comment by aecreations** [comment] 2015-11-05 22:37
Found the cause.  The browser console reports this error on startup:

> SyntaxError: missing ; before statement 
> fxBrowser.js:705:22

Which is due to this offending JavaScript statement:

>    let (that = this) {

Which is no longer supported as of a recent version of Gecko.

Temporary workaround (for Firefox Dev Edition users): Install Clippings 5.0 beta 2, see here for more info: http://aecreations.blogspot.ca/2015/10/clippings-50-beta-1-released-testers.html

Will need to consider pushing out a Clippings 4.1.x maintenance release if Clippings 5.0 won't be ready in time to avoid this issue before Firefox 44.

**Comment by kamidev** [comment] 2015-11-06 12:31
Yes! Your beta fix works for me. I can click the toolbar button, drag selected text or use the context menu. Thanks!

**Comment by nolovelust** [comment] 2015-11-10 22:15
Beta version doesn't work on Thunderbird lightly 44.0a2 (2015-11-10)

**Comment by aecreations** [comment] 2015-11-11 06:51
Confirmed the issue on Thunderbird, with Clippings 5.0 beta 2.  Its cause is the same as [identified above](https://github.com/aecreations/clippings/issues/42#issuecomment-154217883), but while it was fixed for Firefox, it wasn't fixed for Thunderbird.  The Thunderbird issue is being tracked in issue #43.

**Comment by aecreations** [comment] 2016-02-03 05:37
Fixed in Clippings 5.0b2

**Closed by aecreations** 2016-02-03 05:37 UTC
Labels: bug
