### ISSUE TITLE
Shift from legacy Firefox Add-ons to WebExtension

### ISSUE THREAD

**Issue by bunnybooboo** [aecreations/clippings#82] opened 2017-05-05 15:29 UTC
Flagged in the 20170504 version of Firefox Nightly channel as _legacy_. Testing behaviour ahead of Firefox 55 'Release' channel 20170808.

In Firefox 57 (Nightly 20170808 and Release 20171214) Add-ons will be turned OFF. For more information [CLICK HERE](https://wiki.mozilla.org/Add-ons/developer/communication)

Do you have a roadmap to switch to WebExtension?

**Comment by millwood** [comment] 2017-05-05 15:50
it appears that chrome has "canned response" with similar function which will ease my likely move there.

**Comment by aecreations** [comment] 2017-05-08 05:27
From what I've read so far in the MDN documents, the WebExtensions API is severely restrictive with their storage capabilities.  Many Clippings users have hundreds, even thousands, of clippings.  The Storage API that is available won't scale to that much data.  But it is perfect for storing user preferences!

IndexedDB won't work at all for data stored on the local system.  This was an observation in a WebExtensions prototype of Clippings that I developed.

I'm open to other suggestions, but unless there is anything feasible for a WebExtensions version of Clippings, the options I see at this point is to port it to Pale Moon (pending confirmation of their extensions API being compatible with XUL+XPCOM-based extensions), or discontinue it for Firefox and add the ability, in a final Firefox version of Clippings, to export data to different file formats (e.g. Excel, CSV).

**Comment by millwood** [comment] 2017-05-08 13:58
Does chrome have the same limits?  I ask because once firefox kills the old add-ons we'll all be deciding which browser to use and chrome is an obvious possibity,  So I guess I'm hinting that if chrome provides the storage API you need you might go in that direction.

**Comment by JustOff** [comment] 2017-05-10 15:07
> I see at this point is to port it to Pale Moon (pending confirmation of their extensions API being compatible with XUL+XPCOM-based extensions)

At least [Clippings 5.0.2 works well with Pale Moon 27](https://forum.palemoon.org/viewtopic.php?f=44&t=15012&p=112695#p108329).

**Comment by aecreations** [comment] 2017-05-23 06:15
I spent the last 2 weekends on the prototype WebExtensions version of Clippings (tentatively named Clippings/wx).  Porting it to Chrome took minimal effort. Unlike Firefox, Chrome will allow the use of IndexedDB for WebExtensions, which was the showstopper in the original Firefox WebExtension prototype.

I've checked in what I have so far into GitHub (go to the "wx-src" folder in the source repository, in the BRANCH_6-0-WX branch).  It is extremely minimal (i.e., can create and paste clippings, but no Clippings Manager yet -- for now, editing can only be done via direct modification of the data store in Chrome developer tools!), but this has shown that a Chrome version of Clippings is certainly feasible.

So as it stands right now, the options for current Clippings users on Firefox could be as follows:

1. Migrate to Chrome.  Of course, there will need to be a way for users to transfer their clippings over from RDF-based legacy Clippings for Firefox to IndexedDB-based Clippings/wx for Chrome.  WebExtensions have far less capabilities compared to what is possible with the legacy Firefox extensions (there is much heated debate on this elsewhere on the web, so don't get me started), so users will have to expect reduced functionality (e.g., no colored icons for clippings in the Clippings menu, etc.)

2. Port the XUL+XPCOM Clippings extension to Pale Moon (pending further analysis).

3. Add export option to CSV file format, to allow users to move their clippings to another tool.

As Thunderbird isn't moving to WebExtensions, it is expected that XUL+XPCOM Clippings will continue to be supported in that application for the foreseeable future.

**Comment by erosman** [comment] 2017-07-21 07:36
Please note that FF56 will disable all non-Multiprocess addons.

The current storage has the JSON limit of 5mb.
That should be enough for 95% of the users.
My current clipdat2.rdf is 25kb ;)

There is also IndexedDB API and an API is planned.

I have been using Clippings for many years and look forward to continue doing so in future.

**Comment by JustOff** [comment] 2017-07-21 09:37
> Please note that FF56 will disable all non-Multiprocess addons.

@erosman, could you please link me to the corresponding line in the roadmap?

**Comment by erosman** [comment] 2017-07-21 12:01
**could you please link me to the corresponding line in the roadmap?**

I only found out yesterday when I was testing FF56.
There are a lot of undocumented changes. For example FF53 Win32 was around 42mb but FF54 Win32 was only 31mb.
I found out (as one of my addons run into errors) that many JS modules were removed in FF54.

There are many similar changes in FF55 that I only found out after filing a bug (and being told it was intentional).

You can try FF56.0a1

I will look for it in the roadmap and if I find it, I will post it here.

**Comment by JustOff** [comment] 2017-07-21 13:21
@erosman, I only know that FF56 has `extensions.allow-non-mpc-extensions` set to false by default, but switching it to true removes the restriction. I didn't hear anything about plans to disable this before FF57 apocalypse.

**Comment by erosman** [comment] 2017-07-21 14:34
@JustOff That could be the case.. I haven't tested it thoroughly but better to be safe than sorry. ;)

**Comment by aecreations** [comment] 2017-07-22 07:24
Thanks @erosman for the updates.  It looks like Firefox 55 now lets me save the clippings in an IndexedDB database, which I wasn't able to do previously (see [my comment](https://github.com/aecreations/clippings/issues/82#issuecomment-303300514) from May 22).  Now I need to ensure that Clippings/wx is compatible with both Firefox and Chrome.

> The current storage has the JSON limit of 5mb.
> That should be enough for 95% of the users.

I don't want to leave out the 5% who have thousands of clippings in their data source.  The Storage API is not sufficient for Clippings.

> I have been using Clippings for many years and look forward to continue doing so in future.

An announcement on Clippings with Firefox 57 and after is coming soon...

**Comment by aecreations** [comment] 2017-07-30 21:35
Announcement has been posted to the AE Creations Blog: http://aecreations.blogspot.ca/2017/07/compatibility-with-firefox-57.html

To elaborate further on the user migration plan:
- There will be one more release of the legacy XUL+XPCOM+RDF extension, well before Firefox 57, which will automatically save the datasource to the user's Documents folder on their system, whenever a clipping is created, deleted or edited.
- Upon upgrading to the new WebExtension, user will be presented with a screen to import their saved clippings into the Clippings IndexedDB database.  They would need to locate the file that was auto-saved by the legacy Clippings prior to the upgrade.

**Comment by erosman** [comment] 2017-07-31 05:15
> Clippings will be subjected to the limitations of WebExtensions, in that many existing features will no longer be available.  Examples are color-coded labels on clippings, ability to choose data source location, backing up and restoring the data source, and exporting clippings to HTML.

TBH, I wasn't using color-coded labels but there is no reason that it wouldn't work as WebExtension. Furthermore, import/export/restore works as well but has to be user involved. Clippings has to open a Save AS (to backup) and open file input to import/restore but use has to choose the file.

A minimal embedded WebExtension, just for copying database from legacy to WebExtension (and nothing else) would do the job and can be started even now. Just a few lines of code so Clippings would maintain 2 databases (legacy & WebExtension)

Just a few suggestions............
:)

**Comment by aecreations** [comment] 2017-08-01 05:30
I appreciate the suggestions, @erosman !

The color-coded labels are for the menu item icons on the Clippings context submenu; they're meant to let users to categorize their clippings however way they wish. This is just a convenience feature, and many users won't need to color code their clippings.  WebExtensions only allow having an icon for the extension's top-level context menu item (and this would be the extension's icon).  I am still going to save any colored labels that are migrated from legacy Clippings, in case this restriction is removed in the future; but for now it will not be visible from the UI.

Good point about your comments on import/export/restore.  Import and restore should be straightforward (use a `<input type="file">` file uploader, then process the imported data using the FileSystem API).  As for backing up, the JSON, CSV, etc. files could be generated, but how would I be able to invoke a Save As dialog, and then write a file to the user's file system?  There is no WebExtensions API I could find to let me do this.  A workaround would be to generate the export data and put that in a textbox that the user can copy and paste into a text editor running outside of Firefox, but that is a bad user experience.

> A minimal embedded WebExtension, just for copying database from legacy to WebExtension (and nothing else) would do the job and can be started even now. Just a few lines of code so Clippings would maintain 2 databases (legacy & WebExtension)

Due to the extensive integration with Firefox in the browser overlay code (including defining the RDF template for generating the menu items for each clipping, and submenus for the subfolders), I'm reluctant to expend the large amount of effort into converting Clippings to a bootstrapped extension, [which is required](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Embedded_WebExtensions) to have an embedded WebExtension.

**Comment by erosman** [comment] 2017-08-01 09:46
> WebExtensions only allow having an icon for the extension's top-level context menu item (and this would be the extension's icon).
There could be changes to that API
https://bugzilla.mozilla.org/show_bug.cgi?id=1321544

> how would I be able to invoke a Save As dialog
downloads.download() + saveAs (FF52+)

I have already made the import/export code for some of my addons (for the next updates). It is quite easy. Let me now if you need any help ;)

>  I'm reluctant to expend the large amount of effort into converting Clippings to a bootstrapped extension, which is required to have an embedded WebExtension.
Understandable... in that case, I would add a notice to current versions, asking users to backup their data so that it could be imported later. Alternatively, since .clipbak is already on users' file system, it can be retrieved manually by users navigating to it when importing.

**Comment by aecreations** [comment] 2017-08-02 03:17
Thanks again for the pointers!

> I would add a notice to current versions, asking users to backup their data so that it could be imported later. Alternatively, since clipdat2.rdf and .clipbak is already on users' file system, it can be retrieved manually by users navigating to it when importing.

I was thinking about having the pre-Firefox 57 version of legacy Clippings to automatically save/backup data to a file that the user can easily locate once they upgrade to Firefox 57 + Clippings/wx, and have a first-run prompt upon upgrade to locate this backup file and import the backed-up clippings.

**Comment by erosman** [comment] 2017-08-02 19:02
That sounds good. I suggest not waiting for FF57. Mozilla is constantly removing legacy modules (FF54 was 42mb and FF55 is 31mb). I found out a module that I was using in 2 of my legacy addons (no WebExtension API :( ) was removed in FF54 so I had to rewrite a section of the code.

There is no guarantee that legacy addon will work as they are until FF56.

**Comment by bunnybooboo** [comment] 2017-08-03 11:43
57 is now live in Nightly. 56 in Beta and 55 in Release on August 8.

**Comment by bunnybooboo** [comment] 2017-08-22 10:25
Hey I just spotted the `WebExtension` too wahoo!! Really excited now. U2F add-on is also stuffed in Nightly so I have to use Fx55/Fx56 to login and stoked for now Clippings is working in both too. Clippings, to me at least, is just as important in my workflow as U2F. Thanks for keeping the dream alive!

**Comment by aecreations** [comment] 2017-09-27 06:16
Clippings/wx 6.0 alpha 1 is released, for users interested in testing it out.  Details and instructions are [here](https://github.com/aecreations/clippings/wiki).

**Comment by aecreations** [comment] 2017-10-25 06:12
[Clippings/wx 6.0 alpha 2](https://github.com/aecreations/clippings/releases/tag/6.0a2) is released - details and instructions on how to install are posted to the [main wiki page](https://github.com/aecreations/clippings/wiki).

**Comment by aecreations** [comment] 2017-11-01 07:22
[Clippings/wx 6.0 alpha 3](https://github.com/aecreations/clippings/releases/tag/6.0a3) is released.

**Comment by aecreations** [comment] 2017-11-04 07:47
Clippings/wx 6.0 alpha 4 released. This is to allow for testing of upgrading Clippings from 5.5.2 or older to 6.0.  More info in the [main wiki page](https://github.com/aecreations/clippings/wiki).

**Comment by aecreations** [comment] 2017-11-06 09:40
[Clippings/wx 6.0 alpha 5](https://github.com/aecreations/clippings/releases/tag/6.0a5) released. This changes the post-upgrade page from alpha 4 and makes it a general first-run page, targeted to both current and new users.

**Comment by aecreations** [comment] 2017-11-10 09:47
[Clippings 6.0 beta 1](https://github.com/aecreations/clippings/releases/tag/6.0b1) is finally released!  See the blog post on the AE Creations blog for details and how to get it.

**Comment by bunnybooboo** [comment] 2017-11-12 10:43
Fantastic. Nice landing page!
Still a blocker seen in https://bugzilla.mozilla.org/show_bug.cgi?id=1402110 Which the user needs to right click or resize the popup to see it fully rendered.

TTSFox ahve been experiencing same issue. Despite including the supposed workaround described in  bugzilla, bug is still being experienced in all further Firefox Quantum releases. As discussed (HERE)[https://github.com/ettoolong/TTSFox/issues/3]

**Comment by aecreations** [comment] 2017-11-12 18:29
Is this only reproducible on Linux? I've been testing against Windows 7, Windows 10 and macOS Sierra and haven't encountered the blank window issue.  Agreed, this is very concerning. Will test on Ubuntu and OpenSUSE when I get a chance.

**Comment by aecreations** [comment] 2017-11-13 23:46
[Clippings 6.0 beta 2](https://github.com/aecreations/clippings/releases/tag/6.0b2) is released.  More details in [the AE Creations blog](http://aecreations.blogspot.ca/2017/11/clippings-60-beta-2-released.html).  Additional note: beta 2 also includes an attempted fix for the blank window issue on Linux ([Mozilla bug 1402110](https://bugzilla.mozilla.org/show_bug.cgi?id=1402110)).

**Comment by bunnybooboo** [comment] 2017-11-14 09:46
Bug no longer reproduced @aecreations

**Comment by aecreations** [comment] 2017-11-14 10:41
Clippings 6.0 has been submitted to Mozilla Add-ons and should be made available shortly.  I will now close this issue.  Please feel free to create a new issue for any new bugs or feature requests.  Thanks to everyone for their help!

**Closed by aecreations** 2017-11-14 10:41 UTC
Labels: WebExtension
