### ISSUE TITLE
Shortcuts don't work

### ISSUE THREAD

**Issue by pinkunicorn** [aecreations/clippings#448] opened 2024-04-16 12:39 UTC
Steps to reproduce:

    Change to full screen mode on the browser window
    Press Command-Shift-Y to use a shortcut for a clipping. This brings up a dialog on a different virtual desktop (and switches to that desktop). 
    Enter the shortcut for a clipping. (If the clipping has placeholders, this will bring up another dialog.)

Result:
The clipping isn't pasted. The focus stays on the virtual desktop where the dialog was shown, not the full-screen firefox one where the clipping should be.

Reported from Firefox on macOS.

Presumably, this related to https://github.com/aecreations/clippings/issues/432 which behaves very similarly.

(If the Firefox window is not set to full-screen, things work as they should.)

**Comment by aecreations** [comment] 2024-04-17 07:48
Duplicate of issue #432.

**Closed by aecreations** 2024-04-17 07:48 UTC
