### ISSUE TITLE
6.1b2 issues with updating sync-clipping after another computer changes them

### ISSUE THREAD

**Issue by RW-CarlH** [aecreations/clippings#236] opened 2018-10-31 23:51 UTC
Two issues...

The clippings manager doesn't notice that an update is needed until I go to the options and click Settings for sync-clippings and just click OK.

After it reloads, it looks good in the clippings manager, but going to insert a clip shows two synced-clippings folders, as well as a random number of other folders and items from the synced-clippings folder that aren't under either of these synced-clippings folders.     The fix is to turn sync-clippings off and back on and restart Firefox.   Just restarting Firefox alone doesn't fix it.

And when going to turn sync-clippings off, the "Are you sure you want to turn off Sync Clippings" dialog box won't go away after clicking Yes, even though the Yes was recognized.  Can only click "No". 

Having done that, there are now just the two sync-clippings folders shown in the clippings manager as well as the clip-insertion menu, and the clippings manager can remove the extra synced-clippings folder which is easy to identify as the false one because it has a regular folder icon.

**Comment by aecreations** [comment] 2018-11-01 05:47
The Synced Clippings folder updates itself when Firefox is started, but doesn't auto-update itself continuously. An update can be triggered by going into Clippings Manager, right-clicking on the Synced Clippings folder and choosing Reload in the popup menu.

Even so, the other way of triggering an update (by opening the Sync Clippings settings dialog and clicking OK without doing anything) shouldn't cause the issue that you described. Let me see if I can track down the cause.

BTW, when Sync Clippings is turned off, it leaves behind the old Synced Clippings folder, but it becomes a normal, ordinary folder (i.e., it loses the special icon and you can move/delete it in Clippings Manager); this behaviour is by design. The appearance of a brand new Synced Clippings folder when re-enabling Sync Clippings is also by design. But to give users the option to clean things up, I'm thinking about making an option available to delete the Synced Clippings folder when turning off Sync Clippings; this would remove it from Clippings Manager and from the Clippings menu, but the sync file would remain intact, and the user can choose to leave it alone or delete it themselves.

**Comment by RW-CarlH** [comment] 2018-11-01 16:47
OK, but I'm still seeing the wrong behavior I described when triggering the reload prompt as I mentioned.  Try what I described with a complex sync-clippings folder (that has folders inside folders and articles at all levels).   I see a bunch of articles suddenly available at the root, not in any sync-clippings folder old or new, but only from the insertion menu.  Those same not-in-a-folder articles don't appear in the Clippings manager.  So something to look into there.

Also to fully replicate what we had in the prior version of Clippings that stored clippings in a regular file, the sync-clippings syncing needs to happen automatically, without having to request the reload, whenever a newer sync-clippings file is available.    If automatic isn't possible, the next best thing would be to prompt "Sync-clippings has been updated - reload now?"

**Comment by RW-CarlH** [comment] 2018-11-01 16:56
Also FWIW it wasn't obvious to me that right-clicking the sync-clippings folder was where I'd find the reload feature - was expecting it on the Tools menu of the manager, or as a button alongside the sync-clippings Settings and Turn on/off buttons.

**Comment by RW-CarlH** [comment] 2018-11-01 17:10
Also the articles suddenly appearing in the root and dual sync-clippings folders appears just after doing a reload by right-clicking the folder in the manager.   See attached screenshot.
![clippings insertion menu after sync-clippings reload](https://user-images.githubusercontent.com/43094262/47867299-81315080-ddd7-11e8-8af7-1958ca4ede92.png)

**Comment by RW-CarlH** [comment] 2018-11-01 17:21
Another interesting observation - each time I exit Firefox and restart it, the selection of articles appearing in the root of the insertion menu changes.   Meanwhile, clippings manager continues to show this.
![clippings manager after sync-clippings](https://user-images.githubusercontent.com/43094262/47867815-ffdabd80-ddd8-11e8-9c22-4af20e0240f2.png)

**Comment by aecreations** [comment] 2018-11-02 03:30
Thanks for the additional information, and for providing a screen shot! I will try to replicate the conditions that you described that caused the issue to occur.

Also, the suggestions to improve the visibility of reloading the Synced Clippings folder is very helpful. I'm unsure at this point if automatic reloading is something that can be easily done, at least for the 6.1 release, so I can't promise anything right now. But I'll definitely look into adding a reload button in Clippings Manager, and possibly in the extension preferences page, if it makes sense to put it there.

Thanks again for your feedback and your efforts to provide this helpful troubleshooting info. I am hoping that a fix won't be too complicated....

**Comment by aecreations** [comment] 2018-11-03 02:06
@RW-CarlH - How are you storing your sync file on your computers? Are they on a network drive? Or in a folder being synced by Google Drive, Dropbox, etc.?

**Comment by RW-CarlH** [comment] 2018-11-03 15:38
My Sync file is stored on a local Windows server's mapped network drive whose contents remain available when the server is offline.   Generally this file location won't be the cause of any issues. 

I have further information about reproducing the problem - all I have to do is exit and restart Firefox and apparently the reload done at startup has the same effect as a reload requested through Clippings manager.   And the part about the "Are you sure you want to turn off Sync Clippings" dialog box not going away after clicking Yes, that only happens when the clippings manager is left open.

**Comment by aecreations** [comment] 2018-11-04 00:34
The following error appears in the browser console when attempting to turn off Sync Clippings while Clippings Manager is open:

> TypeError: syncFldrTreeNode is null; can't access its "removeClass" property ... clippingsMgr.js:386:5 

This points to a bug in the `gSyncClippingsListener.onDeactivate()` handler in Clippings Manager.

I have not been able to make the other issue happen, where synced items are randomly appearing outside the Synced Clippings folder. Will keep trying.

**Comment by aecreations** [comment] 2018-11-04 19:30
I haven't been able to reproduce the issue with synced clippings and folders randomly appearing outside the Synced Clippings folder. But after analyzing the debug log messages in the browser console, I believe I found the reason for it occurring and have a potential fix, which will be included in the next beta release.

**Comment by RW-CarlH** [comment] 2018-11-04 20:15
Well bother.., I was trimming down my sync-clippings.json in order to send you an example of the problem, and apparently in doing so I trimmed away the problem.   So there must be a syntax problem or corruption in it somewhere.  And that means I guess I'll have to trial-and-error trim away things until the problem stops, then see if putting those things back returns the problem.   You said there's a size limit to the file but I'm pretty sure I'm well under it at about 400K.

**Comment by RW-CarlH** [comment] 2018-11-04 20:19
OK this doesn't make any sense at all... after I renamed my sync-clippings files around to go back to my regular one and reloaded it, I don't see the problem.   Stand by, more testing needed.

**Comment by RW-CarlH** [comment] 2018-11-04 20:53
Got the problem back with my trimmed file, so continuing to trim.

**Comment by aecreations** [comment] 2018-11-05 04:35
I'm a bit surprised that an editing action in Clippings Manager will "fix" the menu problem. In any case, my fix should (hopefully, with fingers crossed) prevent the random sync items from appearing outside the Synced Clippings menu.

**Comment by RW-CarlH** [comment] 2018-11-05 16:04
Re: editing action - I think it needs a delete of a clipping in order to fix the insertion menu issue.

**Comment by aecreations** [comment] 2018-11-09 06:57
Also added an option to remove the Synced Clippings folder when turning off Sync Clippings, as well as the bug where nothing happens when clicking Yes to the confirmation to turn off Sync Clippings. These fixes will be in the next beta release.

**Comment by aecreations** [comment] 2018-11-15 17:17
I've noticed sometimes that on Firefox startup, the Clippings menu is showing duplicated items. Looking at the code, I see that the Clippings menu is being built twice: once when initializing Clippings integration with Firefox, and again when refreshing the Sync Clippings data from the sync file. The latter rebuilds the entire Clippings menu; so if Sync Clippings is turned on, the initial menu build should be suppressed.

This issue appears to be more noticeable on slower systems. I happened to run into this issue when my Windows 10 machine was doing a Windows update, which tends to slow things to a crawl.

**Comment by RW-CarlH** [comment] 2018-11-15 18:09
I believe what you just wrote about is the problem I originally mentioned with the screenshot [up above](https://github.com/aecreations/clippings/issues/236#issuecomment-435113076).   Sometimes it's fixed by reloading the sync-clippings, other times not.   Seeing this on two machines which aren't terribly slow and use SSDs, and the system is fully booted up and not busy when I'm reloading the sync-clippings and that doesn't fix it.   If I keep hitting the reload eventually it will be fixed.  Both machines on beta 3 and Firefox 63.0.1.

**Comment by aecreations** [comment] 2018-11-18 02:48
Latest fix will be available in 6.1 beta 4.

**Comment by RW-CarlH** [comment] 2018-11-18 23:12
Sorry, the thing I wrote about is still happening in beta 4.

**Comment by aecreations** [comment] 2018-11-19 07:07
@RW-CarlH  - could you please specify what behaviours you are still seeing even after installing beta 4? Feel free to reference the above comments if that is easier.

**Comment by aecreations** [comment] 2018-11-20 06:42
@RW-CarlH - I'll need to get you to send me the debug log output from the browser console. 

First, you'll need to enable add-on debugging:
1. Open Firefox, then enter "about:debugging" in the browser's address bar
2. Look for the checkbox labelled "Enable add-on debugging" and tick it

The next time you encounter this issue, please do the following:
1. Open a new browser tab and then enter "about:debugging" in the browser's address bar
2. Locate Clippings in the list of extensions, then click the "Debug" hyperlink to open Firefox developer tools
3. You may see a dialog box appearing, confirming whether you want to allow it to connect. Click OK
4. Once the Developer Tools window opens, click the Console tab. Then select all, copy into a text editor (e.g. Notepad) and save the debugging output to a text file.

Please attach the text file to this issue so that I can examine the debug log.

I'm going through the code again and have found a potential cause for this remaining issue, but I want to review the debug log messages to be sure that I've tracked down the cause.

**Comment by aecreations** [comment] 2018-11-20 06:50
Bingo - I was able to make it happen. Attaching debug log output.
[Clippings debug log.txt](https://github.com/aecreations/clippings/files/2598424/Clippings.debug.log.txt)

**Comment by aecreations** [comment] 2018-11-20 08:05
After further analysis, I believe I have found the cause. To resolve this problem, you (and all other current 6.1 beta users that are experiencing this issue) will need to uninstall Clippings 6.1 beta, close and restart Firefox, then reinstall the Clippings beta release. Make sure you back up your clippings before you uninstall. After reinstalling Clippings, you will need to go into extension preferences and turn on Sync Clippings. It is not necessary to reinstall the Sync Clippings Helper.  Please try this and let me know if that resolves the problem.

Detailed explanation: When the Sync Clippings data is updated, there is supposed to be a brief delay (set to 3 seconds) before the Synced Clippings folder is rebuilt. The delay is a hidden setting (`gPrefs.afterSyncFldrReloadDelay`) that is stored in local storage. This setting will be initialized when users upgrade from Clippings 6.0.x -> 6.1, or install Clippings for the first time _and_ have never had any version prior to 6.1 installed.  Unfortunately, the code that handles the version upgrade doesn't take into account users from 6.1 beta 1/2/3 -> 6.1 beta 4 - so essentially, if you have been using the last few beta releases, then this setting is non-existent. And because the setting is non-existent (`undefined` in the code), the delay after the Sync Clippings update doesn't happen and the Synced Clippings folder is rebuilt immediately. Depending on how long it takes to sync, the sync data update and the menu rebuild may happen out of sequence -- hence the Clippings menu corruption.

**Comment by aecreations** [comment] 2018-11-21 03:35
Thanks for the update.

**Closed** 2018-11-21 03:36 UTC
Labels: bug, fixed

**Comment by RW-CarlH** [comment] 2018-12-13 02:58
I'm familiar with what you say about catching up after waking up - Windows is pretty busy in the minute or two after waking up from sleep.    I had thought the fix was supposed to solve the "slow computer" issue that was thought to be the source of the trouble.

I don't know that another "troubleshoot" button is needed - I can just hit reload to overcome this issue, but I thought you'd want to know that there might still be the potential for it to surface.
